service: s3-bucket-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-south-1
  apiName: ${self:service}
  memorySize: 256 # in MB
  timeout: 30 # in seconds
  environment:
    FILE_UPLOAD_BUCKET_NAME: ${self:custom.bucketName}

custom:
  bucketName: s3-bucket-crud-${self:provider.stage}

functions:
  api:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: Private
